### ISSUE TITLE
Mention resource limits / guarantees

### ISSUE THREAD

**Issue by minrk** [jupyterhub/binder#14]
We should mention resource limits and guarantees in the docs, pointing to [z2jh docs](https://zero-to-jupyterhub.readthedocs.io/en/latest/user-experience.html#set-user-memory-and-cpu-guarantees-limits) on the matter.

mybinder.org currently uses 1G guarantee and 4G limit:

```yaml
jupyterhub:
  singleuser:
    memory:
      guarantee: 1G
      limit: 4G
```
